### ISSUE TITLE
Prospect Notification Showing ID

### ISSUE THREAD

**Issue by Craven73** [xSenpuu/Ultron-BotV1#4]
![image](https://user-images.githubusercontent.com/50681292/209876329-0125b76d-0dce-4011-af1b-113864c0d0b5.png)

Make it display the members name in text after the @.

When using the @, discord messes up and only shows the ID sometimes. Putting the name in raw text will remove confusion

**Comment by xSenpuu** [comment]
working on that now!

**Comment by xSenpuu** [comment]
this is now complete.
